/* AUTO-GENERATED by tools/build-search.py — DO NOT EDIT BY HAND.
   This is the ALL CHAPTERS list shown on chapter pages (rendered by
   main.js with the same .chapter-row classes as the subject pages).
   Source of truth: each subject page's chapter list.
   Regenerate with:  python tools/build-search.py  */
window.LV_CHAPTERS = {
 "data-structures": {
  "subject": "Data Structures",
  "subjectUrl": "subjects/data-structures/",
  "chapters": [
   {
    "num": "01",
    "title": "Introduction to Data Structures",
    "href": "chapter-01.html",
    "desc": "What data structures actually are, how they're classified, and how to think in Big-O before the code even starts.",
    "tags": [
     "FULL NOTES",
     "IMPORTANT QUESTIONS"
    ]
   },
   {
    "num": "02",
    "title": "Arrays",
    "href": "chapter-02.html",
    "desc": "Contiguous memory, the address formula, insertions that shift everything, and the elegance of binary search.",
    "tags": [
     "FULL NOTES",
     "FORMULA SHEET"
    ]
   },
   {
    "num": "03",
    "title": "Linked Lists",
    "href": "chapter-03.html",
    "desc": "Nodes, pointers and structures that grow at runtime — plus the classic arrays-vs-lists showdown.",
    "tags": [
     "FULL NOTES",
     "IMPORTANT QUESTIONS"
    ]
   },
   {
    "num": "04",
    "title": "Stacks & Queues",
    "href": "chapter-04.html",
    "desc": "LIFO and FIFO — the two most examinable structures in existence, from push/pop all the way to circular queues.",
    "tags": [
     "FULL NOTES",
     "ONE-SHOT REVISION"
    ]
   },
   {
    "num": "05",
    "title": "Trees",
    "href": "chapter-05.html",
    "desc": "Hierarchy in data — binary trees, traversals, BSTs and the node-count formulas examiners love.",
    "tags": [
     "FULL NOTES",
     "FORMULA SHEET",
     "ONE-SHOT REVISION"
    ]
   },
   {
    "num": "06",
    "title": "Graphs",
    "href": "chapter-06.html",
    "desc": "Vertices, edges, adjacency matrices and BFS/DFS — the final boss of Semester 1 data structures.",
    "tags": [
     "FULL NOTES",
     "IMPORTANT QUESTIONS"
    ]
   }
  ]
 },
 "engineering-mathematics-i": {
  "subject": "Engineering Mathematics – I",
  "subjectUrl": "subjects/engineering-mathematics-i/",
  "chapters": [
   {
    "num": "01",
    "title": "Limits & Continuity",
    "href": "chapter-01.html",
    "desc": "What functions approach, the standard limits worth memorising, indeterminate forms and the three conditions of continuity.",
    "tags": [
     "FULL NOTES",
     "IMPORTANT QUESTIONS"
    ]
   },
   {
    "num": "02",
    "title": "Differentiation & Applications",
    "href": "chapter-02.html",
    "desc": "Derivatives as limits, the rules, maxima & minima, Rolle's theorem and Lagrange's Mean Value Theorem.",
    "tags": [
     "FULL NOTES",
     "FORMULA SHEET"
    ]
   },
   {
    "num": "03",
    "title": "Integration",
    "href": "chapter-03.html",
    "desc": "Antiderivatives, standard integrals, substitution, by parts (ILATE) and the properties that make definite integrals behave.",
    "tags": [
     "FULL NOTES",
     "FORMULA SHEET"
    ]
   },
   {
    "num": "04",
    "title": "Matrices & Determinants",
    "href": "chapter-04.html",
    "desc": "Matrix types, determinant properties, inverses, rank, and solving systems of equations with Cramer's rule.",
    "tags": [
     "FULL NOTES",
     "ONE-SHOT REVISION",
     "IMPORTANT QUESTIONS"
    ]
   }
  ]
 }
};
